version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker: 
      - image: circleci/node:7
    steps: 
      - checkout
      - run: composer install
      - run: composer require --dev phpunit/phpunit ^8